// Educational Curriculum & Gamified Data Source for EduCore LMS / Gamified Platform

export const COURSE_INFO = {
  id: "cs-201",
  code: "CS 201",
  title: "Data Structures & Algorithms in C",
  subtitle: "Master memory layouts, pointers, dynamic structures, and algorithmic complexity.",
  instructor: {
    name: "Dr. Elena Vance",
    title: "Professor of Computer Systems & Architecture",
    avatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80",
    rating: "4.95 / 5.0",
    students: "14,820 enrolled",
  },
  level: "Intermediate Undergraduate",
  credits: 4,
};

// All 5 Complete Playable Units
export const ALL_UNITS = [
  {
    id: 1,
    number: 1,
    title: "C Foundations & Memory",
    badge: "🌱 Unit 1",
    icon: "🌱",
    subtitle: "5 Playable Levels • Stack vs Heap",
    tip: "Stack memory is fast and automatic; Heap memory is dynamic and manual with malloc!",
    nodes: [
      {
        id: "u1-n1",
        title: "Stack vs Heap",
        subtitle: "Memory Segment Layout",
        type: "lesson",
        status: "completed",
        xp: 20,
        coins: 10,
        icon: "🧱",
        offset: 0,
        summary: "Understand where local variables live compared to dynamic allocations.",
        quiz: {
          question: "Where are local function variables allocated by default in C?",
          code: "void calculate() {\n    int temp = 42; // Where is temp stored?\n}",
          options: [
            { text: "Call Stack Frame", correct: true },
            { text: "Heap Segment", correct: false },
            { text: "Data Segment", correct: false },
            { text: "CPU Cache only", correct: false },
          ],
          explanation: "Local variables declared inside function bodies are placed onto the active Stack Frame.",
        },
      },
      {
        id: "u1-n2",
        title: "Data Types & Sizes",
        subtitle: "sizeof() in Standard C",
        type: "lesson",
        status: "active",
        xp: 25,
        coins: 15,
        icon: "📏",
        offset: -26,
        summary: "Learn fundamental byte sizes for char, int, float, and pointer addresses.",
        quiz: {
          question: "What does sizeof(char) evaluate to in standard C99?",
          code: "printf(\"%zu\\n\", sizeof(char));",
          options: [
            { text: "1 Byte", correct: true },
            { text: "2 Bytes", correct: false },
            { text: "4 Bytes", correct: false },
            { text: "8 Bytes", correct: false },
          ],
          explanation: "By C standard definition, sizeof(char) is guaranteed to always be exactly 1 byte.",
        },
      },
      {
        id: "u1-chest",
        title: "Foundations Treasure",
        subtitle: "Bonus Gold & XP",
        type: "chest",
        status: "active",
        xp: 50,
        coins: 50,
        icon: "🎁",
        offset: 24,
        claimed: false,
      },
      {
        id: "u1-n3",
        title: "Pointer Operators",
        subtitle: "Address & and Dereference *",
        type: "lesson",
        status: "active",
        xp: 30,
        coins: 15,
        icon: "🎯",
        offset: -18,
        summary: "Master reference (&) and dereference (*) operators in pointer manipulation.",
        quiz: {
          question: "How do you read the integer value pointed to by pointer `p`?",
          code: "int x = 99;\nint *p = &x;\n// Which expression yields 99?",
          options: [
            { text: "*p", correct: true },
            { text: "&p", correct: false },
            { text: "p", correct: false },
            { text: "x*", correct: false },
          ],
          explanation: "*p dereferences the pointer address to access the value (99) residing in memory.",
        },
      },
      {
        id: "u1-n4",
        title: "Unit 1 Mastery",
        subtitle: "Pointer Swap Challenge",
        type: "boss",
        status: "active",
        xp: 50,
        coins: 30,
        icon: "👑",
        offset: 0,
        summary: "Implement a pass-by-pointer variable swap in C.",
        quiz: {
          question: "Which function body correctly swaps two integers via pointers?",
          code: "void swap(int *a, int *b) {\n    // Which logic works?\n}",
          options: [
            { text: "int t = *a; *a = *b; *b = t;", correct: true },
            { text: "a = b; b = a;", correct: false },
            { text: "*a = *b; *b = *a;", correct: false },
            { text: "int t = a; a = b; b = t;", correct: false },
          ],
          explanation: "Storing *a in a temporary value before overwriting *a with *b enables a clean swap.",
        },
      },
    ],
  },
  {
    id: 2,
    number: 2,
    title: "Arrays & Dynamic Memory",
    badge: "📦 Unit 2",
    icon: "📦",
    subtitle: "5 Playable Levels • malloc & free",
    tip: "Every malloc() must have a matching free() to prevent memory leaks!",
    nodes: [
      {
        id: "u2-n1",
        title: "Array Contiguity",
        subtitle: "O(1) Direct Offset Math",
        type: "lesson",
        status: "active",
        xp: 20,
        coins: 10,
        icon: "📑",
        offset: 0,
        summary: "Arrays are contiguous blocks where a[i] is computed as *(a + i).",
        quiz: {
          question: "In C, which expression is mathematically identical to arr[i]?",
          code: "int arr[10];",
          options: [
            { text: "*(arr + i)", correct: true },
            { text: "&arr + i", correct: false },
            { text: "*arr + i", correct: false },
            { text: "arr + *i", correct: false },
          ],
          explanation: "Array indexing is syntactic sugar for pointer offset dereferencing: *(arr + i).",
        },
      },
      {
        id: "u2-n2",
        title: "Heap Allocation (malloc)",
        subtitle: "Dynamic Bytes on Demand",
        type: "lesson",
        status: "active",
        xp: 25,
        coins: 15,
        icon: "🏗️",
        offset: -26,
        summary: "Allocating dynamic arrays on the heap using malloc and sizeof.",
        quiz: {
          question: "What does malloc return if the system runs out of memory?",
          code: "int *arr = malloc(1000 * sizeof(int));",
          options: [
            { text: "NULL", correct: true },
            { text: "-1", correct: false },
            { text: "0x00000001", correct: false },
            { text: "Throws an exception", correct: false },
          ],
          explanation: "When memory allocation fails, malloc() returns NULL. Always check if (arr == NULL).",
        },
      },
      {
        id: "u2-chest",
        title: "Memory Treasure",
        subtitle: "Bonus Gold & XP",
        type: "chest",
        status: "active",
        xp: 50,
        coins: 50,
        icon: "🎁",
        offset: 24,
        claimed: false,
      },
      {
        id: "u2-n3",
        title: "Freeing Memory",
        subtitle: "Preventing Leaks & Dangling Pointers",
        type: "lesson",
        status: "active",
        xp: 30,
        coins: 15,
        icon: "🧹",
        offset: -18,
        summary: "Safe deallocation protocols with free() and NULL resetting.",
        quiz: {
          question: "What is best practice immediately after calling free(ptr)?",
          code: "free(ptr);\n// Next best line of code?",
          options: [
            { text: "ptr = NULL;", correct: true },
            { text: "free(ptr); again", correct: false },
            { text: "*ptr = 0;", correct: false },
            { text: "malloc(ptr);", correct: false },
          ],
          explanation: "Setting ptr = NULL prevents accidental dangling pointer dereferences or double-frees.",
        },
      },
      {
        id: "u2-n4",
        title: "Dynamic Vector Boss",
        subtitle: "Amortized O(1) Growth",
        type: "boss",
        status: "active",
        xp: 50,
        coins: 30,
        icon: "👑",
        offset: 0,
        summary: "Geometric resizing strategy with realloc.",
        quiz: {
          question: "Why do dynamic arrays double capacity (2x) when full instead of adding +1?",
          code: "capacity *= 2;\narr = realloc(arr, capacity * sizeof(int));",
          options: [
            { text: "Guarantees amortized O(1) append time", correct: true },
            { text: "C standard forces power-of-two sizes", correct: false },
            { text: "Saves maximum physical RAM", correct: false },
            { text: "Prevents heap fragmentation completely", correct: false },
          ],
          explanation: "Doubling gives O(1) amortized insertion by reducing expensive reallocations to logarithmic frequency.",
        },
      },
    ],
  },
  {
    id: 3,
    number: 3,
    title: "Linked Lists & Pointers",
    badge: "🔗 Unit 3",
    icon: "🔗",
    subtitle: "5 Playable Levels • Nodes & Chains",
    tip: "To insert at head, point new_node->next to head, then update head = new_node!",
    nodes: [
      {
        id: "u3-n1",
        title: "Node Struct Definition",
        subtitle: "Self-Referential Types",
        type: "lesson",
        status: "active",
        xp: 20,
        coins: 10,
        icon: "🏷️",
        offset: 0,
        summary: "Building dynamic node structures with data and pointer to next node.",
        quiz: {
          question: "How is a self-referential Node struct declared in C?",
          code: "typedef struct Node {\n    int data;\n    /* Pointer member */\n} Node;",
          options: [
            { text: "struct Node *next;", correct: true },
            { text: "Node next;", correct: false },
            { text: "void *next_address;", correct: false },
            { text: "int *next;", correct: false },
          ],
          explanation: "Self-referential structs must use pointer syntax 'struct Node *next;' because size of pointer is known.",
        },
      },
      {
        id: "u3-n2",
        title: "Head Insertion",
        subtitle: "O(1) Constant Prepend",
        type: "lesson",
        status: "active",
        xp: 25,
        coins: 15,
        icon: "⬆️",
        offset: -26,
        summary: "Insert a node at the head of a linked list in O(1) time.",
        quiz: {
          question: "What is the time complexity of prepending a node at the head of a linked list?",
          code: "new_node->next = head;\nhead = new_node;",
          options: [
            { text: "O(1) Constant Time", correct: true },
            { text: "O(n) Linear Time", correct: false },
            { text: "O(log n) Logarithmic", correct: false },
            { text: "O(n^2) Quadratic", correct: false },
          ],
          explanation: "Head insertion requires only 2 pointer assignments, which is strictly O(1) constant time.",
        },
      },
      {
        id: "u3-chest",
        title: "Chain Treasure",
        subtitle: "Bonus Gold & XP",
        type: "chest",
        status: "active",
        xp: 50,
        coins: 50,
        icon: "🎁",
        offset: 24,
        claimed: false,
      },
      {
        id: "u3-n3",
        title: "List Traversal",
        subtitle: "Iterating to NULL",
        type: "lesson",
        status: "active",
        xp: 30,
        coins: 15,
        icon: "🚶",
        offset: -18,
        summary: "Traversing linked nodes safely until current pointer reaches NULL.",
        quiz: {
          question: "What loop condition safely traverses every node in a singly linked list?",
          code: "Node *curr = head;\nwhile (/* condition */) {\n    curr = curr->next;\n}",
          options: [
            { text: "curr != NULL", correct: true },
            { text: "curr->next != NULL", correct: false },
            { text: "curr > 0", correct: false },
            { text: "head != NULL", correct: false },
          ],
          explanation: "'curr != NULL' processes every node including the last one before terminating safely.",
        },
      },
      {
        id: "u3-n4",
        title: "Cycle Detection Boss",
        subtitle: "Floyd's Tortoise & Hare",
        type: "boss",
        status: "active",
        xp: 50,
        coins: 30,
        icon: "👑",
        offset: 0,
        summary: "Fast & slow pointer cycle detection algorithm.",
        quiz: {
          question: "In Floyd's cycle detection, by how many steps do slow and fast pointers advance each tick?",
          code: "slow = slow->next;\nfast = /* ??? */;",
          options: [
            { text: "slow 1 step, fast 2 steps", correct: true },
            { text: "slow 1 step, fast 3 steps", correct: false },
            { text: "slow 2 steps, fast 2 steps", correct: false },
            { text: "slow 0 steps, fast 1 step", correct: false },
          ],
          explanation: "If a cycle exists, a pointer advancing 2 steps will always catch a pointer advancing 1 step.",
        },
      },
    ],
  },
  {
    id: 4,
    number: 4,
    title: "Stacks & Queues",
    badge: "🌲 Unit 4",
    icon: "🌲",
    subtitle: "5 Playable Levels • LIFO & FIFO",
    tip: "In LIFO, the element pushed last is the first to be popped!",
    nodes: [
      {
        id: "u4-n1",
        title: "Stack Fundamentals",
        subtitle: "LIFO Principle & Push/Pop",
        type: "lesson",
        status: "completed",
        xp: 20,
        coins: 10,
        icon: "📚",
        offset: 0,
        summary: "Understand the Last-In, First-Out (LIFO) operational rules governing computational stacks.",
        quiz: {
          question: "Which element is removed first when calling pop() on a stack?",
          code: "stack_push(s, 10);\nstack_push(s, 20);\nstack_push(s, 30);\nstack_pop(s);",
          options: [
            { text: "30 (Most recently pushed element)", correct: true },
            { text: "10 (First pushed element)", correct: false },
            { text: "20 (Middle element)", correct: false },
            { text: "Random element based on pointer address", correct: false },
          ],
          explanation: "Stacks operate on LIFO (Last-In, First-Out). The item pushed last (30) is the first to be popped.",
        },
      },
      {
        id: "u4-n2",
        title: "Array Stack Buffer",
        subtitle: "Bounded Array & Top Pointer",
        type: "lesson",
        status: "active",
        xp: 25,
        coins: 15,
        icon: "⚡",
        offset: -26,
        summary: "Implement a bounded stack using a fixed-size C array, integer top index, and overflow checks.",
        quiz: {
          question: "What condition indicates that a bounded array stack with capacity CAP is full?",
          code: "typedef struct {\n    int data[MAX_SIZE];\n    int top;\n} Stack;\n\nbool is_full(Stack *s) {\n    return /* ??? */;\n}",
          options: [
            { text: "s->top == MAX_SIZE - 1", correct: true },
            { text: "s->top == 0", correct: false },
            { text: "s->data[0] == NULL", correct: false },
            { text: "s->top >= MAX_SIZE", correct: false },
          ],
          explanation: "With 0-based array indexing, when top points to MAX_SIZE - 1, every slot (0 to MAX_SIZE - 1) is occupied.",
        },
      },
      {
        id: "u4-chest",
        title: "Stack Treasure",
        subtitle: "Bonus Gold & XP",
        type: "chest",
        status: "active",
        xp: 50,
        coins: 50,
        icon: "🎁",
        offset: 24,
        claimed: false,
      },
      {
        id: "u4-n3",
        title: "Linked Stack Nodes",
        subtitle: "O(1) Dynamic Allocation",
        type: "lesson",
        status: "active",
        xp: 30,
        coins: 15,
        icon: "🔗",
        offset: -18,
        summary: "Eliminate fixed capacity limits by chaining dynamic Node structs with pointer heads.",
        quiz: {
          question: "What is the Big-O time complexity of push and pop operations in a singly-linked stack?",
          code: "void push(Node** head, int val) {\n    Node* n = malloc(sizeof(Node));\n    n->val = val;\n    n->next = *head;\n    *head = n;\n}",
          options: [
            { text: "O(1) Constant Time", correct: true },
            { text: "O(n) Linear Time", correct: false },
            { text: "O(log n) Logarithmic", correct: false },
            { text: "O(n^2) Quadratic", correct: false },
          ],
          explanation: "Inserting and removing strictly at the head node requires only a constant number of pointer swaps: O(1).",
        },
      },
      {
        id: "u4-n4",
        title: "FIFO Circular Queue",
        subtitle: "Ring Buffers & Modulo Indexing",
        type: "lesson",
        status: "active",
        xp: 35,
        coins: 20,
        icon: "🔄",
        offset: 26,
        summary: "Prevent memory drifting in linear arrays by employing circular modulo indexing (rear + 1) % CAP.",
        quiz: {
          question: "How do you calculate the next rear index in a circular queue buffer of size N?",
          code: "void enqueue(Queue *q, int x) {\n    q->rear = /* calculation */;\n    q->data[q->rear] = x;\n}",
          options: [
            { text: "(q->rear + 1) % N", correct: true },
            { text: "q->rear + 1", correct: false },
            { text: "(q->rear * 2) % N", correct: false },
            { text: "q->rear - 1", correct: false },
          ],
          explanation: "The modulo operator % wraps the index back to 0 once it reaches N, forming an endless circular ring.",
        },
      },
      {
        id: "u4-n5",
        title: "Unit 4 Mastery Boss",
        subtitle: "Parentheses Balancer",
        type: "boss",
        status: "active",
        xp: 60,
        coins: 40,
        icon: "👑",
        offset: 0,
        summary: "Mastery checkpoint: Validate matching brackets '()', '{}', '[]' in C compilers using an auxiliary stack.",
        quiz: {
          question: "When parsing a closing bracket '}', what condition signals a syntax violation?",
          code: "bool check_bracket(char c, Stack *s) {\n    if (c == '}') {\n        if (is_empty(s) || pop(s) != '{') return false;\n    }\n    return true;\n}",
          options: [
            { text: "If stack is empty OR popped opener doesn't match '{'", correct: true },
            { text: "Only if the stack is full", correct: false },
            { text: "If top element equals '}'", correct: false },
            { text: "If the string length is even", correct: false },
          ],
          explanation: "A closing brace must match the most recently opened symbol. If empty or mismatched, syntax is invalid.",
        },
      },
    ],
  },
  {
    id: 5,
    number: 5,
    title: "Binary Search Trees",
    badge: "🌳 Unit 5",
    icon: "🌳",
    subtitle: "5 Playable Levels • Hierarchical Trees",
    tip: "In a BST, all keys in the left subtree are smaller, and right subtree are larger!",
    nodes: [
      {
        id: "u5-n1",
        title: "Binary Tree Anatomy",
        subtitle: "Root, Left, and Right Child",
        type: "lesson",
        status: "active",
        xp: 20,
        coins: 10,
        icon: "🌿",
        offset: 0,
        summary: "Every node in a binary tree has at most two children: left and right.",
        quiz: {
          question: "What is the maximum number of nodes in a binary tree of height h (where root height = 0)?",
          code: "// Example: height 0 has 1 node, height 1 has 3 nodes",
          options: [
            { text: "2^(h + 1) - 1", correct: true },
            { text: "2^h", correct: false },
            { text: "h * 2", correct: false },
            { text: "2^(h - 1)", correct: false },
          ],
          explanation: "A full binary tree has 2^0 + 2^1 + ... + 2^h = 2^(h+1) - 1 maximum nodes.",
        },
      },
      {
        id: "u5-n2",
        title: "BST Invariant",
        subtitle: "Left < Root < Right",
        type: "lesson",
        status: "active",
        xp: 25,
        coins: 15,
        icon: "⚖️",
        offset: -26,
        summary: "The ordering invariant enabling O(log n) binary search in trees.",
        quiz: {
          question: "Which traversal of a Binary Search Tree produces elements in strictly ascending sorted order?",
          code: "// Left -> Root -> Right",
          options: [
            { text: "In-Order Traversal", correct: true },
            { text: "Pre-Order Traversal", correct: false },
            { text: "Post-Order Traversal", correct: false },
            { text: "Level-Order BFS", correct: false },
          ],
          explanation: "In-order traversal visits left subtree, current root, then right subtree, naturally outputting sorted keys.",
        },
      },
      {
        id: "u5-chest",
        title: "Tree Treasure",
        subtitle: "Bonus Gold & XP",
        type: "chest",
        status: "active",
        xp: 50,
        coins: 50,
        icon: "🎁",
        offset: 24,
        claimed: false,
      },
      {
        id: "u5-n3",
        title: "BST Search Complexity",
        subtitle: "Balanced vs Degenerate Trees",
        type: "lesson",
        status: "active",
        xp: 30,
        coins: 15,
        icon: "🔍",
        offset: -18,
        summary: "Best-case logarithmic search vs worst-case linear skew.",
        quiz: {
          question: "What is the worst-case search time complexity in an un-balanced degenerate BST?",
          code: "// Inserting 1, 2, 3, 4, 5 in sorted order creates a linear line",
          options: [
            { text: "O(n) Linear Time", correct: true },
            { text: "O(log n) Logarithmic", correct: false },
            { text: "O(1) Constant", correct: false },
            { text: "O(n log n)", correct: false },
          ],
          explanation: "If items are inserted in sorted order, the BST degrades into a linked list with O(n) height.",
        },
      },
      {
        id: "u5-n4",
        title: "Grand Mastery Boss",
        subtitle: "Tree Deletion & Invariant",
        type: "boss",
        status: "active",
        xp: 60,
        coins: 40,
        icon: "👑",
        offset: 0,
        summary: "Deleting a node with two children using in-order successor replacement.",
        quiz: {
          question: "When deleting a BST node with two children, with which node should it be replaced?",
          code: "Node* delete_node(Node* root, int key);",
          options: [
            { text: "The minimum node in its right subtree (In-order Successor)", correct: true },
            { text: "The maximum node in its right subtree", correct: false },
            { text: "Any random leaf node", correct: false },
            { text: "The tree root node", correct: false },
          ],
          explanation: "The in-order successor is the smallest value greater than the target, perfectly preserving the BST invariant.",
        },
      },
    ],
  },
];

// For backwards compatibility
export const PATH_NODES = ALL_UNITS[3].nodes;

// Leaderboard Data
export const LEADERBOARD_USERS = [
  { rank: 1, name: "Marcus Chen", xp: 2450, streak: 21, avatar: "🦁", league: "Diamond" },
  { rank: 2, name: "Sophia Rodriguez", xp: 2120, streak: 14, avatar: "🦊", league: "Diamond" },
  { rank: 3, name: "Arjun Mehta", xp: 1890, streak: 32, avatar: "⚡", league: "Diamond" },
  { rank: 4, name: "Alex Turner (You)", xp: 1450, streak: 7, avatar: "🦉", league: "Diamond", isCurrent: true },
  { rank: 5, name: "Emma Watson", xp: 1320, streak: 9, avatar: "🐼", league: "Diamond" },
  { rank: 6, name: "Liam O'Connor", xp: 1190, streak: 5, avatar: "🐯", league: "Diamond" },
  { rank: 7, name: "Yuki Tanaka", xp: 980, streak: 12, avatar: "🐺", league: "Diamond" },
  { rank: 8, name: "David Kim", xp: 840, streak: 3, avatar: "🐸", league: "Diamond" },
];

// In-App Shop Items
export const SHOP_ITEMS = [
  {
    id: "streak-freeze",
    title: "Streak Freeze",
    description: "Equip a protective ice shield! Preserves your daily streak if you miss a study session.",
    icon: "🧊",
    cost: 150,
  },
  {
    id: "heart-refill",
    title: "Full Heart Refill",
    description: "Instantly restore your lives back to 5 full hearts so you can keep practicing uninterrupted.",
    icon: "❤️",
    cost: 100,
  },
  {
    id: "double-xp",
    title: "Double XP Potion",
    description: "Earn 2x XP for all quiz answers and completed challenges for the next 30 minutes!",
    icon: "⚡",
    cost: 200,
  },
  {
    id: "golden-owl",
    title: "Golden Terminal Badge",
    description: "Exclusive retro amber glowing avatar skin for the Diamond League leaderboards.",
    icon: "👑",
    cost: 400,
  },
];

// User Profile & Achievements
export const ACHIEVEMENTS = [
  { id: "ach-1", title: "Wildfire Streak", desc: "Reach a 7-day continuous study streak", icon: "🔥", progress: "7/7" },
  { id: "ach-2", title: "Pointer Wizard", desc: "Complete all pointer arithmetic and heap memory labs", icon: "🧙‍♂️", progress: "4/4" },
  { id: "ach-3", title: "Stack Champion", desc: "Build both bounded array and dynamic linked stacks", icon: "🥞", progress: "3/3" },
  { id: "ach-4", title: "Diamond League Elite", desc: "Finish in the top 5 of the weekly diamond leaderboard", icon: "💎", progress: "Rank #4" },
];
