"use client";
/* eslint-disable react/jsx-no-comment-textnodes */
import { useEffect, useState } from "react";
import { buildCampaign, getRank, tierConfig } from "./questionBank";
import usePlayer from "./usePlayer";

const dsaTopics = [
  { name: "Arrays", icon: "[ ]", detail: "Indexing, traversal and array operations", level: 0 },
  { name: "Linked Lists", icon: "→", detail: "Nodes, pointers and list operations", level: 5 },
  { name: "Stacks", icon: "▤", detail: "LIFO operations and applications", level: 1 },
  { name: "Queues", icon: "⇥", detail: "FIFO, circular and priority queues", level: 2 },
  { name: "Searching", icon: "⌕", detail: "Linear and binary search", level: 3 },
  { name: "Sorting", icon: "≋", detail: "Core sorting algorithms and complexity", level: 8 },
  { name: "Trees", icon: "⌘", detail: "Binary trees, BSTs and traversal", level: 4 },
  { name: "Hash Tables", icon: "#", detail: "Hashing, buckets and collisions", level: 6 },
  { name: "Graphs", icon: "◇", detail: "BFS, DFS and shortest paths", level: 7 },
  { name: "Recursion", icon: "↻", detail: "Base cases and recursive thinking", level: 9 },
];

function StackQuestionVisual({ prompt }) {
  const [items, setItems] = useState(() => (prompt.match(/\d+/g) || []).slice(-3).map(Number));
  const [status, setStatus] = useState("READ FROM BOTTOM → TOP");
  function push() { if (items.length >= 5) { setStatus("OVERFLOW — STACK IS FULL"); return; } const value = Math.floor(Math.random() * 90) + 10; setItems((currentItems) => [...currentItems, value]); setStatus(`PUSHED ${value} TO TOP`); }
  function pop() { if (!items.length) { setStatus("UNDERFLOW — STACK IS EMPTY"); return; } const value = items[items.length - 1]; setItems((currentItems) => currentItems.slice(0, -1)); setStatus(`POPPED ${value} FROM TOP`); }
  return <div className="question-stack-lab"><div><small>LIVE STACK VISUALIZER</small><b>Which item leaves first?</b><p>In LIFO, the newest top item is removed first.</p><code>{status}</code><div><button onClick={push} type="button">+ PUSH</button><button onClick={pop} type="button" disabled={!items.length}>− POP</button></div></div><div className="question-stack"><span>TOP ↓</span><div>{[...items].reverse().map((item, index) => <i key={`${item}-${items.length - index}`}>{item}</i>)}</div><strong>BOTTOM</strong></div></div>;
}

export default function Home() {
  const [screen, setScreen] = useState("home"), [mode, setMode] = useState("dsa"), [level, setLevel] = useState(0), [choice, setChoice] = useState(null), [lives, setLives] = useState(3), [xp, setXp] = useState(0), [hint, setHint] = useState(false), [message, setMessage] = useState(""), [loginOpen, setLoginOpen] = useState(false), [profileOpen, setProfileOpen] = useState(false), [pendingMode, setPendingMode] = useState("dsa"), [pendingLevel, setPendingLevel] = useState(null), [selectedTopic, setSelectedTopic] = useState(null), [stackItems, setStackItems] = useState([12, 27, 41]), [stackMessage, setStackMessage] = useState("TOP → 41"), [authError, setAuthError] = useState(""), [email, setEmail] = useState(""), [password, setPassword] = useState(""), [createMode, setCreateMode] = useState(false);
  const { user, stats, loading, login, loginWithPassword, createAccount, resetPassword, logout, saveRun, completeLevel, finishRun } = usePlayer();
  const campaign = buildCampaign(mode), current = campaign[level], rank = getRank(xp), tier = tierConfig[current?.tier || 0];
  useEffect(() => {
    if (!loading && user && stats.activeGame && stats.activeGame.currentLevel < buildCampaign(stats.activeGame.mode).length) {
      const run = stats.activeGame;
      const resume = window.setTimeout(() => { setMode(run.mode); setLevel(run.currentLevel || 0); setLives(run.lives || 3); setXp(run.xp || 0); setChoice(Number.isInteger(run.selectedChoice) ? run.selectedChoice : null); setHint(Boolean(run.hint)); setScreen("game"); }, 0);
      return () => window.clearTimeout(resume);
    }
  }, [loading, user, stats.activeGame]);
  useEffect(() => {
    if (user && screen === "game") saveRun(mode, { currentLevel: level, lives, xp, selectedChoice: choice, hint });
  }, [choice, hint, level, lives, mode, saveRun, screen, user, xp]); // Save in-progress quiz interaction without replacing level-completion checkpoints.
  function enterCampaign(nextMode, targetLevel = null) { const queuedTopic = typeof nextMode === "string" && nextMode.startsWith("topic:") ? nextMode.split(":") : null; const queuedLevel = queuedTopic ? Number(queuedTopic[2]) : typeof nextMode === "string" && nextMode.startsWith("level:") ? Number(nextMode.split(":")[1]) : null; const campaignMode = queuedTopic ? queuedTopic[1] : queuedLevel === null ? nextMode : "dsa"; const selectedLevel = targetLevel ?? queuedLevel; const saved = stats.campaigns?.[campaignMode]; const canResume = saved && saved.currentLevel < buildCampaign(campaignMode).length; const run = { currentLevel: selectedLevel ?? (canResume ? saved.currentLevel : 0), lives: canResume ? (saved.lives || 3) : 3, xp: canResume ? (saved.xp || 0) : 0, selectedChoice: null, hint: false, completedLevels: saved?.completedLevels || [] }; setMode(campaignMode); setScreen("game"); setLevel(run.currentLevel); setChoice(null); setLives(run.lives); setXp(run.xp); setHint(false); setMessage(""); saveRun(campaignMode, run); }
  function start(nextMode = "dsa") { const mapLevel = screen === "home" ? { dsa: 0, code: 1, bugs: 2 }[nextMode] : null; const campaignMode = mapLevel === null || mapLevel === undefined ? nextMode : "dsa"; if (!user) { setPendingMode(mapLevel === null || mapLevel === undefined ? campaignMode : `level:${mapLevel}`); setPendingLevel(mapLevel ?? null); setLoginOpen(true); return; } enterCampaign(campaignMode, mapLevel); }
  function launchTopic(challengeMode) { const topicLevel = selectedTopic?.level ?? 0; if (!user) { setPendingMode(`topic:${challengeMode}:${topicLevel}`); setPendingLevel(topicLevel); setSelectedTopic(null); setLoginOpen(true); return; } setSelectedTopic(null); enterCampaign(challengeMode, topicLevel); }
  function pushStack() { if (stackItems.length >= 5) { setStackMessage("STACK OVERFLOW — POP FIRST"); return; } const value = Math.floor(Math.random() * 90) + 10; setStackItems((items) => [...items, value]); setStackMessage(`PUSH ${value} — NEW TOP`); }
  function popStack() { if (!stackItems.length) { setStackMessage("STACK UNDERFLOW — NOTHING TO POP"); return; } const removed = stackItems[stackItems.length - 1]; setStackItems((items) => items.slice(0, -1)); setStackMessage(`POP ${removed} — ITEM REMOVED`); }
  async function handleLogin() { setAuthError(""); try { await login(); setLoginOpen(false); enterCampaign(pendingMode, pendingLevel); } catch (error) { if (error?.code !== "auth/popup-closed-by-user") setAuthError("Google sign-in failed. Please try again."); } }
  async function handlePasswordLogin(event) { event.preventDefault(); setAuthError(""); try { if (createMode) await createAccount(email.trim(), password); else await loginWithPassword(email.trim(), password); setLoginOpen(false); enterCampaign(pendingMode); } catch (error) { const messages = { "auth/invalid-credential": "Wrong password, or this email only uses Google login. Try Google or create a password account.", "auth/user-not-found": "No password account exists for this email. Create an account first.", "auth/wrong-password": "The password is incorrect. Use Forgot password to reset it.", "auth/email-already-in-use": "This email already has an account. Sign in or use Google.", "auth/weak-password": "Use a password with at least 6 characters.", "auth/invalid-email": "Enter a valid email address.", "auth/operation-not-allowed": "Email/password login is disabled in Firebase Console. Enable it under Authentication → Sign-in method.", "auth/network-request-failed": "Network error. Check your connection and try again.", "auth/too-many-requests": "Too many attempts. Wait a moment or reset your password." }; setAuthError(messages[error?.code] || `Firebase sign-in failed (${error?.code || "unknown error"}).`); } }
  async function handlePasswordReset() { setAuthError(""); if (!email.trim()) { setAuthError("Enter your email above before requesting a reset."); return; } try { await resetPassword(email.trim()); setAuthError("Password reset email sent. Check your inbox and spam folder."); } catch (error) { const messages = { "auth/invalid-email": "Enter a valid email address.", "auth/operation-not-allowed": "Email/password login is disabled in Firebase Console.", "auth/too-many-requests": "Too many requests. Please wait and try again." }; setAuthError(messages[error?.code] || `Password reset failed (${error?.code || "unknown error"}).`); } }
  async function handleLogout() { await logout(); setProfileOpen(false); setScreen("home"); }
  function navigateTo(id) { setScreen("home"); window.setTimeout(() => document.getElementById(id)?.scrollIntoView({ behavior: "smooth" }), 0); }
  function next() { if (level === campaign.length - 1) { finishRun(mode); setScreen("win"); } else { setLevel(level + 1); setChoice(null); setHint(false); setMessage(""); } }
  function submit() { if (choice === current.answer) { const alreadyCompleted = stats.campaigns?.[mode]?.completedLevels?.includes(level); const earned = alreadyCompleted ? 0 : current.xpReward; const nextXp = xp + earned; setXp(nextXp); completeLevel(mode, level, { currentLevel: level + 1, lives, xpReward: current.xpReward }); setMessage(`LEVEL CLEAR  +${earned} XP`); setTimeout(next, 650); return; } const remaining = lives - 1; setLives(remaining); setChoice(null); saveRun(mode, { currentLevel: level, lives: remaining, xp }); setMessage(remaining ? "LIFE LOST — TRY AGAIN" : "OUT OF LIVES"); if (!remaining) setTimeout(() => setScreen("lost"), 700); }
  return <main className={`shell ${screen === "home" ? "storefront" : ""}`}><div className="grid-bg" />{user && <details className="profile-panel"><summary>PROFILE</summary><div><b>{user.displayName || user.email?.split("@")[0] || "Player"}</b><span>{stats.totalXp} XP · {Object.values(stats.campaigns || {}).reduce((total, run) => total + (run.completedLevels?.length || 0), 0)} / 150 LEVELS CLEARED</span>{["dsa", "code", "bugs"].map((campaignMode) => <small key={campaignMode}>{campaignMode.toUpperCase()}: {stats.campaigns?.[campaignMode]?.completedLevels?.length || 0} / 50 COMPLETE</small>)}</div></details>}
    <header className="topbar"><button className="wordmark" onClick={() => navigateTo("top")}><span>DS</span> DSA DUNGEON</button><nav><button onClick={() => navigateTo("quests")}>Quests</button><button onClick={() => navigateTo("benefits")}>Rewards</button><button onClick={() => navigateTo("about")}>How it works</button></nav><div className="account">{loading ? <span className="account-loading">LOADING...</span> : user ? <div className="user-menu"><span className="avatar">{user.displayName?.charAt(0).toUpperCase() || user.email?.charAt(0).toUpperCase() || "P"}</span><span className="user-name"><b>{user.displayName || user.email?.split("@")[0] || "Player"}</b><small>{stats.totalXp} XP · HIGH {stats.highScore}</small></span><button onClick={handleLogout}>LOG OUT</button></div> : <button className="login-nav" onClick={() => { setPendingMode("dsa"); setLoginOpen(true); }}>SIGN IN</button>}</div></header>
    {screen === "home" && <section className="dungeon-map"><div className="map-heading"><div><small>THE LEARNING PATH</small><h1>Master the dungeon, one structure at a time.</h1><p>Choose a topic, then pick how you want to train.</p></div><div className="map-progress"><b>{Object.values(stats.campaigns || {}).reduce((total, run) => total + (run.completedLevels?.length || 0), 0)}</b><span>CHALLENGES<br/>CLEARED</span></div></div><div className="topic-path">{dsaTopics.map((topic, index) => <button key={topic.name} className={`topic-node node-${index % 4}`} onClick={() => setSelectedTopic({ ...topic, index })}><i>{topic.icon}</i><span><small>LEVEL {String(index + 1).padStart(2, "0")}</small><b>{topic.name}</b><em>{topic.detail}</em></span><strong>→</strong></button>)}</div></section>}
    {selectedTopic && <div className="topic-backdrop" role="dialog" aria-modal="true" aria-labelledby="topic-title" onMouseDown={(event) => { if (event.target === event.currentTarget) setSelectedTopic(null); }}><div className={`topic-modal ${selectedTopic.name === "Stacks" ? "stack-topic-modal" : ""}`}><button className="topic-close" onClick={() => setSelectedTopic(null)} aria-label="Close">×</button><div className="topic-symbol">{selectedTopic.icon}</div><small>LEVEL {String(selectedTopic.index + 1).padStart(2, "0")}</small><h2 id="topic-title">{selectedTopic.name}</h2><p>{selectedTopic.detail}. Choose your challenge type.</p>{selectedTopic.name === "Stacks" && <div className="stack-lab"><div className="stack-copy"><small>INTERACTIVE LIFO LAB</small><b>Last in, first out</b><p>Push adds to the top. Pop removes the top item.</p><div className="stack-actions"><button onClick={pushStack}>+ PUSH</button><button onClick={popStack} disabled={!stackItems.length}>− POP</button></div><code>{stackMessage}</code></div><div className="stack-machine"><span className="stack-top">TOP ↓</span><div className="stack-values">{[...stackItems].reverse().map((item, index) => <i key={`${item}-${stackItems.length - index}`}>{item}</i>)}</div><strong>STACK</strong></div></div>}<div className="challenge-types"><button onClick={() => launchTopic("dsa")}><i>?</i><span><b>DSA Trial</b><small>Test your concepts</small></span><strong>→</strong></button><button onClick={() => launchTopic("code")}><i>&lt;/&gt;</i><span><b>Code Forge</b><small>Complete the C code</small></span><strong>→</strong></button><button onClick={() => launchTopic("bugs")}><i>!</i><span><b>Bug Hunt</b><small>Find and fix errors</small></span><strong>→</strong></button></div></div></div>}
    {screen === "game" && <section className="game"><aside><small>CURRENT CAMPAIGN</small><h3>{current.type}</h3><div className="tier-badge" style={{borderColor:tier.color,color:tier.color}}>{tier.name}</div><div className="counter"><b>{String(current.tierQuestion).padStart(2,"0")}</b> / {String(current.tierTotal).padStart(2,"0")}</div><div className="bar"><i style={{width:`${((level + 1) / campaign.length) * 100}%`}}/></div><div className="player-stats"><span>XP <b>{xp}</b></span><span>RANK <b>{rank.name}</b></span></div><div className="rank-progress"><i style={{width:`${Math.min(100, xp / rank.next * 100)}%`}}/><small>{rank.name === "LEGEND" ? "MAX RANK" : `${rank.next - xp} XP TO NEXT RANK`}</small></div><div className="life"><span className="hearts">{"♥".repeat(lives)}{"♡".repeat(3-lives)}</span><span><b>{lives} LIVES LEFT</b><small>WRONG ANSWERS COST ONE</small></span></div><button onClick={() => setScreen("home")}>× EXIT QUEST</button></aside><article><div className="panel-head"><span>QUESTION {level + 1} / {campaign.length}</span><b>REWARD +{current.xpReward} XP</b></div><h2>{current.title}</h2>{current.code && <div className="editor"><div><i/><i/><i/><span>challenge.c</span></div><pre>{current.code}</pre></div>}<p className="instruction">{current.prompt}</p>{current.title === "Stack behavior" && <StackQuestionVisual key={`${mode}-${level}`} prompt={current.prompt}/>}<div className="options">{current.choices.map((item, i) => <button key={item} className={choice === i ? "active" : ""} onClick={() => setChoice(i)}><b>{String.fromCharCode(65 + i)}</b>{item}<i>→</i></button>)}</div><div className="submit"><button className="hint-button" onClick={() => setHint(!hint)}>💡 {hint ? "HIDE HINT" : "USE HINT"}</button><span className={message.includes("CLEAR") ? "success" : "error"}>{message}</span><button className="primary" disabled={choice === null || message.includes("CLEAR")} onClick={submit}>CONFIRM →</button></div>{hint && <p className="hint">// HINT: {current.hint}</p>}</article></section>}
    {(screen === "win" || screen === "lost") && <section className={`ending ${screen === "lost" ? "lost" : ""}`}><code>{screen === "win" ? "CAMPAIGN_COMPLETE" : "RUN_ENDED"}</code><h2>{screen === "win" ? "QUEST\nCLEARED." : "OUT OF\nLIVES."}</h2><p>{screen === "win" ? `You earned ${xp} XP and finished as ${rank.name}.` : `You reached ${rank.name} with ${xp} XP. Refill your hearts and try again.`}</p><button className="primary" onClick={() => start(mode)}>PLAY AGAIN</button><button className="ghost" onClick={() => setScreen("home")}>LOBBY</button></section>}
    {loginOpen && <div className="login-backdrop" role="dialog" aria-modal="true" aria-labelledby="login-title"><div className="login-modal"><button className="modal-close" onClick={() => setLoginOpen(false)} aria-label="Close">×</button><span className="login-logo">DS</span><p>PLAYER ACCESS</p><h2 id="login-title">{createMode ? "Create your account" : "Sign in to play"}</h2><span className="login-copy">Save your XP, highest score, and rank with Firebase.</span><button className="google-login" onClick={handleLogin}><b>G</b> CONTINUE WITH GOOGLE</button><div className="auth-divider"><span>OR USE EMAIL</span></div><form className="email-login" onSubmit={handlePasswordLogin}><label>EMAIL<input type="email" value={email} onChange={(event) => setEmail(event.target.value)} placeholder="player@example.com" autoComplete="email" required /></label><label>PASSWORD<input type="password" value={password} onChange={(event) => setPassword(event.target.value)} placeholder="6 or more characters" autoComplete={createMode ? "new-password" : "current-password"} minLength="6" required /></label><button type="submit">{createMode ? "CREATE ACCOUNT" : "SIGN IN WITH PASSWORD"}</button></form>{!createMode && <button className="forgot-password" onClick={handlePasswordReset}>FORGOT PASSWORD?</button>}{authError && <small className={authError.includes("sent") ? "auth-success" : "auth-error"}>{authError}</small>}<button className="auth-switch" onClick={() => { setCreateMode(!createMode); setAuthError(""); }}>{createMode ? "Already registered? Sign in" : "New player? Create an account"}</button><small>Login is required before entering a campaign.</small></div></div>}
    <footer><span>© 2026 DSA DUNGEON</span><span>LEARN C · MASTER DSA · FIX BUGS</span></footer></main>;
}
